version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in the paramter store in AWS Systems Manager 
    SNYK_TOKEN: "SNYK_TOKEN"
    SNYK_BASELINE_ORG: "SNYK_ORG"
    SNYK_PROJ: "SNYK_BASELINE_PROJ"

phases:
  install:
    commands:
      - npm install -g snyk
      - npm install -g snyk-delta

  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - snyk test --json --print-deps | snyk-delta --baselineOrg "${SNYK_BASELINE_ORG}" --baselineProject "${SNYK_PROJ}"